# SPDX-FileCopyrightText: 2025 UL Solutions - Software Intensive Systems
#
# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    path: zephyr-security-showcase

  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect

  projects:
    - name: nrf
      repo-path: sdk-nrf
      remote: ncs
      revision: v3.1.0
      clone-depth: 1
      import:
        name-allowlist:
          - cmsis_6
          - hal_nordic
          - mbedtls
          - nrfxlib
          - oberon-psa-crypto
          - trusted-firmware-m
          - zephyr
