name: "General CI checks"

defaults:
  run:
    working-directory: ws

on:
  schedule:
    - cron: "31 1 * * *" # Runs daily at 1:31
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    name: "Build and test showcase"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/zephyrproject-rtos/ci:v0.28.2
      options: '--entrypoint /bin/bash'
    env:
      ZEPHYR_SDK_INSTALL_DIR: /opt/toolchains/zephyr-sdk-0.17.2
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          show-progress: true
          path: ws/zephyr-security-showcase

      - name: Set up virtual environment + install west
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install --upgrade pip west
          echo "$PATH" > $GITHUB_PATH

      - name: Add LLVM toolchain to PATH
        run: |
          echo "/usr/lib/llvm-20/bin" >> $GITHUB_PATH

      - name: Setup Zephyr workspace
        run: |
          west init -l ./zephyr-security-showcase
          west update

      - name: Install Zephyr python dependencies
        run: |
          . .venv/bin/activate
          pip install -r zephyr/scripts/requirements.txt

      - name: Setup SCA
        run: |
          pip install codechecker

      - name: Build and analyze sample application
        run: |
          # TODO: FIXME Normally, one would use `west twister` to build the sample application,
          # but the `/ns` board is missing the pm_config.h. One would need to investigate why
          # this happens and how to fix this. Right now, it is good enough to build this one sample manually.
          west build -p auto -b nrf7002dk/nrf5340/cpuapp/ns zephyr-security-showcase/samples/ul/pkcs11/ -- \
            -DZEPHYR_SCA_VARIANT=codechecker \
            -DCODECHECKER_ANALYZE_OPTS="-i;/__w/zephyr-security-showcase/zephyr-security-showcase/ws/zephyr-security-showcase/sca_skipfile;--timeout;60;-d;clang-diagnostic-reserved-identifier" \
            -DCODECHECKER_PARSE_OPTS="-i;/__w/zephyr-security-showcase/zephyr-security-showcase/ws/zephyr-security-showcase/sca_skipfile" \
            -DCODECHECKER_PARSE_EXIT_STATUS="TRUE"

      - name: Run Zephyr security showcase unit tests (with coverage)
        run: |
          west twister -p unit_testing \
            --outdir twister-out --inline-logs \
            --coverage --coverage-basedir ./zephyr-security-showcase \
            -T ./zephyr-security-showcase/

      - name: Upload Twister Reports
        uses: actions/upload-artifact@v4
        with:
          name: twister-reports
          path: |
            ws/twister-out/coverage/index.html
            ws/twister-out/twister.json
            ws/twister-out/twister.xml
            ws/twister-out/twister_report.xml

  publish-test-results:
    name: "Publish Tests Results"
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    if: (!cancelled())
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: "artifacts/**/twister_report.xml"
