name: "General CI checks"

on:
  schedule:
    - cron: "31 1 * * *" # Runs daily at 1:31
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    name: "Build and test showcase"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/zephyrproject-rtos/ci:v0.28.2
      options: '--entrypoint /bin/bash'
    env:
      ZEPHYR_SDK_INSTALL_DIR: /opt/toolchains/zephyr-sdk-0.17.2
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          show-progress: true
          path: zephyr-security-showcase

      - name: Add LLVM toolchain to PATH
        run: |
          echo "/usr/lib/llvm-20/bin" >> $GITHUB_PATH

      - name: Restore Zephyr workspace cache
        uses: actions/cache@v4.2.4
        with:
          path: |
            modules
            nrf
            nrfxlib
            zephyr
          key: zephyr-workspace-${{ runner.os }}-${{ hashFiles('zephyr-security-showcase/west.yml') }}
          restore-keys: |
            zephyr-workspace-${{ runner.os }}-

      - name: Setup Zephyr workspace
        run: |
          west init -l ./zephyr-security-showcase
          west update

      - name: Setup SCA
        run: |
          pip install codechecker

      - name: Build and analyze sample application
        run: |
          # TODO: FIXME Normally, one would use `west twister` to build the sample application,
          # but the `/ns` board is missing the pm_config.h. One would need to investigate why
          # this happens and how to fix this. Right now, it is good enough to build this one sample manually.
          west build -p auto -b nrf7002dk/nrf5340/cpuapp/ns zephyr-security-showcase/samples/ul/pkcs11/ -- \
            -DZEPHYR_SCA_VARIANT=codechecker \
            -DCODECHECKER_ANALYZE_OPTS="--file;$PWD/zephyr-security-showcase/*;--timeout;60;-d;clang-diagnostic-reserved-identifier" \
            -DCODECHECKER_PARSE_OPTS="--file;$PWD/zephyr-security-showcase/*" \
            -DCODECHECKER_PARSE_EXIT_STATUS="TRUE"

      - name: Run Zephyr security showcase unit tests (with coverage)
        run: |
          west twister -p unit_testing \
            --outdir twister-out --inline-logs \
            --coverage --coverage-formats xml \
            --coverage-basedir ./zephyr-security-showcase \
            -T ./zephyr-security-showcase/

      - name: Upload Twister Reports
        uses: actions/upload-artifact@v4
        with:
          name: twister-reports
          path: |
            twister-out/coverage/coverage.xml
            twister-out/twister.json
            twister-out/twister.xml
            twister-out/twister_report.xml

  publish-test-results:
    name: "Publish Tests Results"
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    if: (!cancelled())
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: "artifacts/**/twister_report.xml"

      - name: Create code coverage report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: artifacts/**/coverage.xml
          format: markdown
          hide_complexity: true
          output: both

      - name: Add coverage report to PR
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
