name: Build and Push 'Optimized' Zephyr (CI) Docker Image

on:
  workflow_dispatch:
    inputs:
      ZEPHYR_DOCKER_TAG:
        description: 'Zephyr Docker CI image (e.g., v1.2.3)'
        required: true

jobs:
  build-and-push:
    name: "Build and push own Zephyr Docker CI image"
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4.2.4

      - name: Generate final image tag
        id: final_docker_tag
        run: echo "value=${{ github.event.inputs.ZEPHYR_DOCKER_TAG }}-$(date -u +'%Y%m%d-%H%M%S')" >> "$GITHUB_OUTPUT"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and (maybe) push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/main' }}
          build-args: |
            CI_IMAGE_VERSION=${{ github.event.inputs.ZEPHYR_DOCKER_TAG }}
          tags: |
            ghcr.io/${{  github.repository }}/ci:${{ steps.final_docker_tag.outputs.value }}
